# Site settings
title: David Omar Design
email: david@davidomardesign.com
description: "Illustration Art Digital."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: davidomar
github_username:  lopezdavidomar

# Build settings
markdown: kramdown
permalink: pretty
